### ISSUE TITLE
Nativescript Windows runtime: Language and API completeness, feature status?

### ISSUE THREAD

**Issue by mike-ense** [NativeScript/windows-runtime#5]
Hi,

What features exist currently in the Windows runtime, with respect to bridging the underlying language with Javascript, and reflecting the Windows API into Javascript?

And, which features that are needed to make a Windows Phone/desktop UI spin, are absent?

(I see some mentionings of what's there and what's not at https://github.com/NativeScript/NativeScript/issues/254 , but I think that was discussed quite long ago. Also this may be a better issue to discuss this in as that issue regards *whether* there is Windows support, as a kind of poll, whereas this issue discusses *how* the Windows support works/is made/should be made.)

Will be very happy to learn to know. Thanks for making Nativescript, it's a fantastic project. With some luck, the Windows runtime can be used by skillful developers both for Windows Phone apps, and for Windows Desktop programs. If *you* provide the base runtime, open source developers such as me can contribute and debug. Thanks!

**Comment by mike-ense** [comment]
@tjvantoll your attention and comments would be much appreciated!

**Comment by mike-ense** [comment]
@jasssonpet @fealebenpae bump!! Could you elaborate on this one please?

**Comment by mike-ense** [comment]
@jasssonpet @fealebenpae , my question to you (and any other devs who are working with the NS UWP binding) is:

 * As you have dug into this problem, is what you see, that you will be able to do it?

 * Do you see with certitude that the NS JS binding model that you have made to work for ObjC/Apple and Java/Android, will work for the UWP/C++ environment also?

 * Please feel free to elaborate on how you will implement this, how it will work more specifically, when you get to implementation later.

While I understand that the UWP binding is not prioritary for you now, the UWP binding may be a strategic future asset of some of your users. In the small amount of communication that the devs have made to the public, I picked up a kind-of questioning about whether the Nativescript JS language binding model would actually work at all in on the UWP. It's with the background of that unclarity, that I ask you to respond to the above. Thanks!

**Comment by EmilStoychev** [comment]
There is no ongoing work on the Windows runtime. We don't have this in our short term plan either as we don't see demand for it.
